board: st: common: Fix board_get_alt_info_mtd()
Since MTD devices are partioned, we got the following
error when command "dfu 0" is executed:

DFU alt info setting: done
ERROR: Too many arguments for nor0
ERROR: DFU entities configuration failed!
ERROR: (partition table does not match dfu_alt_info?)

[Backport of commit b40f67a63586 ("board: st: common: Fix board_get_alt_info_mtd()")]

Change-Id: I25ba0e5fd48d4f839a401cf6583fab54c25b61ab
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/u-boot/+/338195
Fixes: 31325e1b8b9c ("stm32mp1: dynamically build DFU_ALT_INFO")
Signed-off-by: Patrice Chotard <patrice.chotard@foss.st.com>
Reviewed-by: Patrick Delaunay <patrick.delaunay@foss.st.com>
Signed-off-by: Patrick Delaunay <patrick.delaunay@foss.st.com>